### ISSUE TITLE
Use clean install

### ISSUE THREAD

**Issue by larsvilhuber** [AEADataEditor/docker-stata#1]
The current dockerfile cheats and uses a pre-installed Tar file

Use the workflow file from https://github.com/ledwindra/continuous-integration-stata/blob/main/.github/workflows/basic.yml and make the build clean from downloaded file.

**Comment by larsvilhuber** [comment]
@ledwindra has re-organized repo to create an action (great!), so here the key parts that need to be incorporated into the Dockerfile here:

```
# install stata
mkdir ~/Downloads
cd ~/Downloads
wget -O Stata$2Linux64.tar.gz $1
cd /tmp/
mkdir statafiles
cd statafiles
tar -zxf ~/Downloads/Stata$2Linux64.tar.gz
cd /usr/local
mkdir stata$2
cd stata$2
yes | /tmp/statafiles/install
export PATH=/usr/local/stata$2:$PATH
./stinit << EOF
y
y
$3
$4
$5
y
y
$6
$7
y
EOF

```

and where (order matters)
```
inputs:
  url:
    required: true
    description: 'The link to your Stata installer'
  version:
    required: true
    description: 'Your Stata version'
  serial-number:
    required: true
    description: 'Your Stata serial number (this will be encrypter so that nobody can see it)'
  code:
    required: true
    description: 'Your Stata code license (this will be encrypter so that nobody can see it)'
  authorization:
    required: true
    description: 'Your Stata authorization license (this will be encrypter so that nobody can see it)'
  first-name:
    required: true
    description: 'Your Stata first-name display'
  last-name:
    required: true
    description: 'Your Stata last-name display'
  stata-edition:
    required: true
    description: 'Your Stata edition. Choices: stata, stata-se, stata-mp)'
    default: 'stata'
```
